version: '3'

services:
  rust_devcontainer:
    image: rust-tutorial-image
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ../:/workspace
    working_dir: /workspace